name: documentation
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: set version
        run: |
          VERSION=$(git describe --tags --always 2>/dev/null || echo "dev")
          echo "PROJECT_NUMBER = $VERSION" >> Doxyfile
      - name: Generate Documentation
        uses: mattnotmitt/doxygen-action@edge
      - name: Publish generated content to GitHub Pages
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.2
        with:
          dir: doc/html
          branch: gh-pages
          token: ${{ secrets.ACCESS_TOKEN }}